### ISSUE TITLE
empty face

### ISSUE THREAD

**Issue by phatyh** [shivam1410/fangpenlin-avataaars-generator-angular#7]
https://shivam1410.github.io/fangpenlin-avataaars-generator-angular/?top=shorthair_shortwaved&accessories=blank&hairColor=browndark&hatColor=gray01&facialHair=moustache_fancy&facialHairColor=pastel_pink&clothes=graphic_shirt&clothColor=heather&eyes=hearts&eyebrow=sad_concerned&mouth=smile&skin=brown&face=mouth&graphic=bat

**Comment by shivam1410** [comment]
Thanks @phatyh, For pointing this out, It has been rectified.
